### ISSUE TITLE
How to use t-test and beta-binomial generalized linear model in package aod:: betabin to test the difference in cluster abundances (cell counts) between MS donors and control donors

### ISSUE THREAD

**Issue by Jihong528** [chenlingantelope/MSscRNAseq2019#3]
Hello, I am so sorry that I can't understand how to use the aod:: betabin package to test the difference in cluster abundances (cell counts) between MS donors and control donors.  I have download the Betabinom.R from your github, but I can't find the  count file(count = read.table(paste(filename, '.count.txt',sep=''))), so I don't know how to run the function, could you please provide the file? Thanks a lot for your help.

**Comment by chenlingantelope** [comment]
Hi Jihong, 
Sorry for the late reply. count.txt is a matrix that stores the number of cells per sample per cell type. The rows are each sample, and columns are cell types. I will upload it to the folder where the .R file is. 
Best,
Chenling
